version: "3.2"
services:
  change-me:
    build:
        context: ./
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
    ports:
        - 8080:8080
    volumes:
        - ./:/go/src/change-me